/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.devin.api;

import com.devin.api.core.ClientOptions;
import com.devin.api.core.Suppliers;
import com.devin.api.resources.imdb.AsyncImdbClient;
import java.util.function.Supplier;

public class AsyncDevinApiClient {
    protected final ClientOptions clientOptions;

    protected final Supplier<AsyncImdbClient> imdbClient;

    public AsyncDevinApiClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.imdbClient = Suppliers.memoize(() -> new AsyncImdbClient(clientOptions));
    }

    public AsyncImdbClient imdb() {
        return this.imdbClient.get();
    }

    public static AsyncDevinApiClientBuilder builder() {
        return new AsyncDevinApiClientBuilder();
    }
}
