/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.devin.api;

import com.devin.api.core.ClientOptions;
import com.devin.api.core.Environment;
import okhttp3.OkHttpClient;

public final class AsyncDevinApiClientBuilder {
    private ClientOptions.Builder clientOptionsBuilder = ClientOptions.builder();

    private Environment environment;

    public AsyncDevinApiClientBuilder url(String url) {
        this.environment = Environment.custom(url);
        return this;
    }

    /**
     * Sets the timeout (in seconds) for the client. Defaults to 60 seconds.
     */
    public AsyncDevinApiClientBuilder timeout(int timeout) {
        this.clientOptionsBuilder.timeout(timeout);
        return this;
    }

    /**
     * Sets the maximum number of retries for the client. Defaults to 2 retries.
     */
    public AsyncDevinApiClientBuilder maxRetries(int maxRetries) {
        this.clientOptionsBuilder.maxRetries(maxRetries);
        return this;
    }

    /**
     * Sets the underlying OkHttp client
     */
    public AsyncDevinApiClientBuilder httpClient(OkHttpClient httpClient) {
        this.clientOptionsBuilder.httpClient(httpClient);
        return this;
    }

    public AsyncDevinApiClient build() {
        clientOptionsBuilder.environment(this.environment);
        return new AsyncDevinApiClient(clientOptionsBuilder.build());
    }
}
