/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.devin.api;

import com.devin.api.core.ClientOptions;
import com.devin.api.core.Suppliers;
import com.devin.api.resources.imdb.ImdbClient;
import java.util.function.Supplier;

public class DevinApiClient {
    protected final ClientOptions clientOptions;

    protected final Supplier<ImdbClient> imdbClient;

    public DevinApiClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.imdbClient = Suppliers.memoize(() -> new ImdbClient(clientOptions));
    }

    public ImdbClient imdb() {
        return this.imdbClient.get();
    }

    public static DevinApiClientBuilder builder() {
        return new DevinApiClientBuilder();
    }
}
