/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.devin.api.core;

/**
 * This class serves as the base exception for all errors in the SDK.
 */
public class DevinApiException extends RuntimeException {
    public DevinApiException(String message) {
        super(message);
    }

    public DevinApiException(String message, Exception e) {
        super(message, e);
    }
}
